# Generated by Django 5.1.1 on 2024-09-06 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("o_score", models.FloatField(default=0)),
                ("c_score", models.FloatField(default=0)),
                ("e_score", models.FloatField(default=0)),
                ("a_score", models.FloatField(default=0)),
                ("n_score", models.FloatField(default=0)),
                ("numerical", models.FloatField(default=0)),
                ("spatial", models.FloatField(default=0)),
                ("perceptual", models.FloatField(default=0)),
                ("verbal", models.FloatField(default=0)),
                ("logical", models.FloatField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_type", models.CharField(max_length=50)),
                ("question_text", models.TextField()),
                ("selected_option", models.CharField(max_length=100)),
                ("correct_answer", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.userprofile",
                    ),
                ),
            ],
        ),
    ]
