# Generated by Django 5.1.1 on 2024-09-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='perceptual_ability',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spatial_ability',
        ),
        migrations.AlterField(
            model_name='question',
            name='subcategory',
            field=models.CharField(choices=[('o_score', 'O Score'), ('c_score', 'C Score'), ('e_score', 'E Score'), ('a_score', 'A Score'), ('n_score', 'N Score'), ('numerical', 'Numerical'), ('verbal', 'Verbal'), ('logical', 'Logical')], max_length=50),
        ),
    ]
